# -*- mode: ruby -*-
# vi: set ft=ruby :

#================#
# Ansible Server #
#================#

# Vagrant.configure("2") : Vagrant version 2
# config.vm.define : vagrant 명령어를 사용할 때 이용될 tag 
Vagrant.configure("2") do |config|
  config.vm.define "ansible-server" do |cfg|
    # provisioning 할 운영체제 선택
    cfg.vm.box = "centos/7"
    cfg.vm.provider "virtualbox" do |vb|
      # 가상 머신 이름 지정
      vb.name = "Ansible-Server"
    end
    # 가상 머신 Hostname 지정
    cfg.vm.host_name = "ansible-server"
    # 네트워크 지정
    cfg.vm.network "private_network", ip: "192.168.56.10"
    cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
    # host와 사용하게 될 공유 폴더 지정
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", inline: "yum install epel-release -y" 
    cfg.vm.provision "shell", inline: "yum install ansible -y"
    cfg.vm.provision "file", source: "ansible_env_ready.yml", destination: "ansible_env_ready.yml"
    cfg.vm.provision "shell", inline: "ansible-playbook ansible_env_ready.yml"
  end
end
